### ISSUE TITLE
Braking should not become Reverse

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#1]
If brake=1.0 the car goes into Reverse mode and drives backwards.

**Comment by tdev** [comment]
`controller.mainController.setGearboxMode('realistic')`

must be executed to fix the arcade shifting behavior :)

Needs to be fixed in the Lua code.

**Comment by Signaltonsalat** [comment]
Made the vehicle default to the `realistic` gearbox and added [current gear to the vehicle state dictionary](https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGPy.req_vstate) and `gear` option to the [input of the vehicle control](https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGPy.vcontrol).
