### ISSUE TITLE
LIDAR example fails to run, Assertion error

### ISSUE THREAD

**Issue by vNemesis** [BeamNG/BeamNGpy#123]
Hi,

I am attempting to run the LIDAR tour example but i get this error when the scenario loads.

![image](https://user-images.githubusercontent.com/26275454/118382586-1fc8da00-b5ef-11eb-9568-0b37906597ea.png)

It seems an assertion is failing when running the poll_sensors method.

**Comment by nebriv** [comment]
@vNemesis I'm also running into this issue - I see you closed it, did you find a solution?

**Comment by vNemesis** [comment]
@nebriv No sorry, I no longer needed to use it. I did find that there was a similar issue when using a camera. it seems to be caused when using the step part of the code.

![image](https://user-images.githubusercontent.com/26275454/121051291-41158400-c7b1-11eb-89b3-6d67775ea5ee.png)

Some combination of removing these these lines stopped the issue when using a camera, not sure if it works the for the LIDAR as well sorry!
