### ISSUE TITLE
Can't render more than 1 Scenario camera

### ISSUE THREAD

**Issue by DanAmador** [BeamNG/BeamNGpy#139]
Good day, again :) 

I tried having multiple scenario cameras at the same time, but the [render camera](https://github.com/BeamNG/BeamNGpy/blob/e0f2e648f044137a92f77f1e272dfcf851fc7ad9/src/beamngpy/beamng.py#L954) method hangs indefinitely if the scenario contains more than one camera. 

Everything gets encoded correctly and it seems the request is sent correctly, but I never receive a response from it.

**Comment by pascale-commits** [comment]
Hi, I found that the data attribute in the Camera object doesn't get updated at all for scenario cameras. [Commit that should resolve this bug.](https://github.com/BeamNG/BeamNGpy/commit/92573ac9db6eb2ca3a1369552689a715195bcdde)
But I couldn't replicate your issue. If you encounter it again, please post the log output of the simulation, from BeamNGpy and state what BeamNG.tech and BeamNGpy version you are using. 🙏
