### ISSUE TITLE
State sensor gets automatically detached

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#151]
Dear all, 
after updating from BeamNG.research 1.7.0.1 to BeamNG.tech 0.23.5_1 I notices that once a scenario is over, all the sensors attached to a Vehicle are automatically detached. This includes also the `state` sensors which is a default sensor attached to it.

This breaks our code that reuses the same Vehicle object across simulations; however, I am not sure how we should handle this case: should we forbid the reuse of Vehicle objects or should ensure that the `state` sensor is never detached? Also, IMHO no sensors should be attached by default as this breaks the API, e.g., why State sensor should be different from any other sensor?)

**Comment by aivora-beamng** [comment]
As the state sensor is always attached to every vehicle, we decided to fix it by not detaching it when disconnecting from a scenario. Reuse of Vehicle objects should be possible now.

Fixed in BeamNGpy v1.22 (https://pypi.org/project/beamngpy/1.22/).
