### ISSUE TITLE
Camera sensors always create three shared memories?

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#155]
It seems that each camera sensor, although configured with `depth=false` and `annotation=false`, results in creating three shared memories to store colours, annotation and depth. Is this the intended behaviour?

**Comment by aivora-beamng** [comment]
Hi,
thanks for bringing this up! Indeed, it does not make sense to create shared memories for sensor data that are not requested. We have the fix for this behaviour ready for the upcoming version of BeamNG.tech.

**Comment by aivora-beamng** [comment]
Fixed in BeamNG.tech 0.25 / [BeamNGpy 1.23](https://github.com/BeamNG/BeamNGpy/tree/v1.23). If the issue still persists for you, please open a new issue!
