### ISSUE TITLE
Use Freeroam UI/controls when started in beamngpy

### ISSUE THREAD

**Issue by fpetry** [BeamNG/BeamNGpy#156]
When starting the simulation through a python script, not the complete UI/controls are available.
Switching cars with [TAB] or resetting the Car with [INSERT] is not possible.

We plan to have multiple  scripts connected to one main simulation and for overview and demonstration purposes would like to be able to switch/reset cars.

It would also be nice to be able to spawn cars in the GUI, that can then be controlled by beamngpy "agents" using the ID.

I could not find if this is already possible. I could imagine a flag like "completeGUI=true" or similar.

**Comment by aivora-beamng** [comment]
Hi,
you can enable the complete UI/controls in scenarios in in-game options: `Options -> Gameplay -> General -> Competitive scenario conditions (uncheck it)`.

For your second issue:
Cars spawned in GUI can be controlled by BeamNGpy agents. You can see the way how in the `multi_client.ipynb` example; when you spawn a vehicle through GUI, you will see it in the list of vehicles returned by `client.get_current_vehicles()`.

A snippet:
1. Create the scenario.
```python
bng = BeamNGpy('localhost', 64256)
bng.open()

scenario = Scenario('smallgrid', 'test')
av = Vehicle('vehicle', model='etk800')
scenario.add_vehicle(av, pos=(0, -10, 0))
scenario.make(bng)
bng.load_scenario(scenario)
bng.start_scenario()
```
2. Spawn the vehicle through GUI.
3. Find the spawned vehicle in the list of current vehicles, connect to it and switch to it (this can be done from any client connected).
```python
active_vehicles = bng.get_current_vehicles()
print(active_vehicles)

active_vehicles['clone'].connect(bng)
bng.switch_vehicle(active_vehicles['clone'])
```
