### ISSUE TITLE
 road example does not create new road

### ISSUE THREAD

**Issue by zeedev01** [BeamNG/BeamNGpy#16]

**Comment by alessiogambi** [comment]
@zeedev01 Can you provide a minimal description and steps to reproduce the issue?

**Comment by zeedev01** [comment]
@alessiogambi 
 1. compile the road_definition.py from examples 
 2. It successfully executes but doesn't display anything like road or scenario , it just open the BeamNG  game console and only has one button to go back to the start screen..
