### ISSUE TITLE
Spawning vehicles at speed (accel, jerk) greater than zero

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#160]
It should be possible to spawn new vehicles at a given (physical) state, i.e., with a given speed, acceleration, etc..

**Comment by Diminati** [comment]
Totally agree! I would like to see this feature being added, especially on the ai_set_script for example.

Some heavy vehicles take a lot of time to get up to speed and that's a lot of time lost for each run.
That would also help the procedural creation of scenarios with multiple cars.

**Comment by alessiogambi** [comment]
@aivora-beamng @dstark481 Is there any progress or news about this feature?

**Comment by aivora-beamng** [comment]
Hi, this feature should make it into the next major release (BeamNG.tech 0.25).

**Comment by aivora-beamng** [comment]
Implemented in BeamNG.tech 0.25 / [BeamNGpy 1.23](https://github.com/BeamNG/BeamNGpy/tree/v1.23).

On a spawned vehicle, you can use the [set_velocity](https://beamngpy.readthedocs.io/en/latest/beamngpy.html#beamngpy.vehicle.Vehicle.set_velocity) method.
