### ISSUE TITLE
Spawn vehicle in specific configuration

### ISSUE THREAD

**Issue by ASionville** [BeamNG/BeamNGpy#164]
Hello!

How can I spawn a car in a given configuration, like those available in free roam?
How to spawn a Vivace in 110d configuration, for example?

**Comment by aivora-beamng** [comment]
Hi,
this functionality is a little bit hidden, you have to use the `partConfig` field of `vehicle.options` (as you can see in the snippet). In future versions of the library, we may expose this functionality to be more accessible.

```python
from beamngpy import BeamNGpy, Vehicle, Scenario
beamng = BeamNGpy('localhost', 64256)
beamng.open()

scenario = Scenario('west_coast_usa', 'config_spawn')

vehicle = Vehicle('ego', model='vivace')
vehicle.options['partConfig'] = 'vehicles/vivace/vivace_110d_M.pc'
scenario.add_vehicle(vehicle, pos=(-725.365, 92.4684, 118.437),
                     rot_quat=(-0.006, -0.0076, 0.921, -0.389))

scenario.make(beamng)
beamng.load_scenario(scenario)
beamng.start_scenario()
```

You can find all the different `.pc` configurations in the BeamNG.tech folder, for example `content/vehicles/vivace.zip/vehicles/vivace/*.pc`. You can also provide a path to your custom part configuration file.

**Comment by ASionville** [comment]
Thanks !!
