### ISSUE TITLE
Vehicle.ai_drive_in_lane(True) should not break AIControl HUD

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#17]
Steps to reproduce:
    - Start BeamNG with -console, load scenario
    - visualize AIControl HUD, change AI mode to "Manual"
    - set In Lane to "on"
    - set target waypoint (NOTE it is important to set In Lane before the way point otherwise the car will NOT stay in the lane since the beginning)
     - change AI mode to "Disabled"

Check that there's no error messages in BeamNG Console.

    - Start BeamNG.py and  call:
        - vehicle.ai_set_mode("manual")
        - vehicle.ai_drive_in_lane(True) *I also tried with "on" and "'on'"
        - vehicle.ai_set_waypoint(<waypoint>)

Check that AI Control HUD **does not update to reflect the manual mode**

         - set In Lane to "on" or "off" 

Check in the BeamNG console that the following error message is printed:
```056.716|E|libbeamng.lua.V|*** FATAL LUA ERROR: [string "string"]:1: attempt to call field 'driveInLane' (a string value)
056.717|E|libbeamng.lua.V|=============== Stack Traceback >> START >>
056.718|E|libbeamng.lua.V|(1) main chunk of [string "string"] at line 1
056.718|E|libbeamng.lua.V|--------------- << END <<
056.718|E|libbeamng.lua.V|*** while executing this line: ai.driveInLane("on")
056.719|E|libbeamng.lua.V|*** in chunk: string```

**Comment by Signaltonsalat** [comment]
Should finally be fixed in the newest release (1.6.1.0) of .research and BeamNGpy (1.11.)
