### ISSUE TITLE
BeamNGTech access error

### ISSUE THREAD

**Issue by mayureshb7** [BeamNG/BeamNGpy#174]
Hi Team,

As instructed in the tech demonstration, I'm able to launch BeamNGTech by exe but unable to launch it through Python API.
I'm getting below mentioned error and need your feedback on it for me to resolve the issue.

![image](https://user-images.githubusercontent.com/99101076/174659902-3d655db3-1986-4136-9f30-b0a141713e14.png)

Warm Regards,
Mayuresh Bhosale

**Comment by aivora-beamng** [comment]
Hi, your BeamNG.tech and BeamNGpy versions are out-of-sync, please check https://github.com/BeamNG/BeamNGpy#compatibility (you should use BeamNGpy v1.23 with BeamNG.tech 0.25).

**Comment by mayureshb7** [comment]
Thank you for your response, I was able to resolve this issue
