### ISSUE TITLE
How to use BeamNGpy to let the AI vehicle to whistle？

### ISSUE THREAD

**Issue by naner34** [BeamNG/BeamNGpy#177]
When I control the vehicle in the game, I can Press the H key to sound the car horn. But do you know how to use BeamNGpy to let the AI vehicle whistle？I got no idea.
Thanks for your help！

**Comment by aivora-beamng** [comment]
Hi,
with a spawned vehicle (`vehicle`) object, you can use `vehicle.queue_lua_command('electrics.horn(true)')` to turn the horn on and `vehicle.queue_lua_command('electrics.horn(false)')` to turn the horn off.

**Comment by naner34** [comment]
Thanks, it really works. It helps me a lot.
