### ISSUE TITLE
the format of 'info.json'

### ISSUE THREAD

**Issue by Mayuemei** [BeamNG/BeamNGpy#178]
I applied the scenarios generated by other software to the 0.22 version of Beamng.tech, the message "info.json" is missing when running as follows. 
![This is an image about error](https://s2.loli.net/2022/07/02/Cv498pJg5wiRBh3.jpg)

Then I generate a JSON file according to BeamNG.py, the content is as follows: 
![This is an image about content from 'info.json'](https://s2.loli.net/2022/07/02/mPrYJdQvHVTqXpj.png)

But it  reported 'parse error'. Why does this problem occur, or if the format is wrong, is there a more accurate content format of ‘info.json’?

**Comment by aivora-beamng** [comment]
Hi,
for valid examples of `info.json` files, you can look into the assets of BeamNG.tech. For BeamNG.tech 0.22, you can check out for example `levels\GridMap\info.json`. Try to change your `info.json` into the format of that file.
