### ISSUE TITLE
How to use the data of "track editor" to build track in beamngpy?

### ISSUE THREAD

**Issue by naner34** [BeamNG/BeamNGpy#182]
Hello, I want to build a track using beamngpy, but it is not easy to do that. So I use the "track editor" in the Beamng.tech to build a track in the "smallgrid"map. The track is as follows.
![635584dbf72a14d21533cfded323574](https://user-images.githubusercontent.com/54585256/179357983-a8b6779c-4958-470f-8c23-cde396305f48.png)
However, the track can not be saved in this level. So I can not use the code `scenario = Scenario('smallgrid', 'example')` to load this track in beamngpy.

I find a json file of that track(scenario_sn.json). I wonder：
1. If there is a way to use world editor to save the track in this level，then beamngpy can load the level to get the track.
2. If there is a way to let beamngpy read the track data(i.e. the json file as image below) to rebuild the track.

![image](https://user-images.githubusercontent.com/54585256/179358312-a63f7887-8b87-4eff-8b2e-2104c5a9824b.png)

**Comment by dstark481** [comment]
Hi,

Thanks for your query.

The tracks are actually separate from the levels, so if you want a track on a level you can load a level then load a track.

Regarding your query 2, this is something we have on our to-do list, but have not got round to yet.  There is currently no way to do this, unfortunately.

Best regards,
BeamNG Tech team.

**Comment by naner34** [comment]
Hello dstark481,

Thank you for your response! Looking forward to the fufuture update.

**Comment by aivora-beamng** [comment]
Hi again,
if you want to experiment with loading TrackBuilder scenarios before the feature is implemented, you can use the following script:
```python
from beamngpy import BeamNGpy, Scenario, Vehicle
from pathlib import Path

def load_trackbuilder_track(beamng, path):
    file = Path(path).name
    
    lua_code = f'''extensions.load("util_trackBuilder_splineTrack")
local tb = extensions.util_trackBuilder_splineTrack
tb.ignoreCapsForMeshes = true
tb.load(readJsonFile([[{path}]]), true, nil, nil, true, false)

for _, objName in ipairs(scenetree.findClassObjects("ProceduralMesh")) do
  if not string.find(objName, ".json") then
    local obj = scenetree.findObject(objName)
    if obj then
      obj:setName('{file}'..'-'..obj.name)
    end
  end
end
tb.unloadAll()
extensions.unload("util_trackBuilder_splineTrack")
'''
    beamng.queue_lua_command(lua_code)

beamng = BeamNGpy('localhost', 64256)
beamng.open()

scenario = Scenario('smallgrid', 'trackbuilder')
vehicle = Vehicle('ego_vehicle', model='pickup', licence='PYTHON')
scenario.add_vehicle(vehicle, pos=(0, 0, 0), rot_quat=(0, 0, 0, 1))

scenario.make(beamng)
beamng.load_scenario(scenario)
beamng.start_scenario()

load_trackbuilder_track(beamng, r'\levels\gridmap_v2\qwer.json')

beamng.teleport_vehicle(vehicle.vid, (217.36, -262.46, 220.38), rot_quat=(0, 0, 0, 1))
```

**Comment by naner34** [comment]
Thank you very much. It really help me a lot. Now I can rebuild the track that has been already saved.
