### ISSUE TITLE
Changing light bar mode

### ISSUE THREAD

**Issue by purple-mesh** [BeamNG/BeamNGpy#184]
In BeamNG, 

* **light bar** can be toggled using `shift + n` -- and this can be modified using Vehicle class's `set_lights()`
* **light bar modes** can be changed using `alt + shift + n`

Would it be possible to cycle through light bar modes using BeamNGpy?

For context, I am trying to programmatically control the traffic light in the game. My current approach is using this [traffic light mod](https://www.beamng.com/resources/functional-traffic-light-props-mod-award-winner.16757/) and then controlling it with this BeamNGpy.

Any advice or suggestion regarding my current approach or any other alternative approach would be appreciated.

**Comment by aivora-beamng** [comment]
Hi,
you can run a custom vehicle Lua chunk which does the equivalent of the `alt + shift + n` shortcut. That is,
```python
chunk = '''for _,v in pairs(controller.getControllersByType('lightbar')) do v.toggleMode() end'''
vehicle.queue_lua_command(chunk)
```

where `vehicle` is an instance of a `BeamNGpy.Vehicle` object already connected to BeamNGpy. Let me know if you need further support!

**Comment by purple-mesh** [comment]
Thanks @aivora-beamng I have tested this and confirmed that it works as expected. Appreciate the prompt response!
