### ISSUE TITLE
Can the vehicle in Beamng(v0.25) achieve the same glare intensity as a real-life high beam?

### ISSUE THREAD

**Issue by sainan-zhang** [BeamNG/BeamNGpy#189]
Hello, can the vehicle in beamng(v0.25) have high beams that dazzle the eyes? I have set 'headlights=2' in the function 'beamng.set_lights', But the light intensity of the vehicle is not as strong as the high beam in real life. Can you help me achieve this? Looking forward to your reply! Thanks very much!

**Comment by sainan-zhang** [comment]
Hi! Thanks for your detailed reply. I have set the value of "lightBrightness" to 1 and created a new vehicle mod according to your suggestion. But the light intensity of the vehicle is still not as strong as the high beam in real life. In the following figure, I copied the blue vehicle, then changed the value of "lightBrightness" to 1.0 to get the red vehicle. That is, the difference between red vehicle and blue vehicle is only the "lightBrightness" value. Is there any other way to make the vehicles in Beamng achieve the same glare intensity as a real-life high beam? Can you give me some help? Looking forward to your reply. Thank you very much!
![c423091c62f8c79db2a1779c9806027](https://user-images.githubusercontent.com/53167747/194263061-d8cc6eb9-d86f-4206-aea6-720589632985.jpg)

**Comment by aivora-beamng** [comment]
Hello, you can also increase `lightBrightness` to values higher than 1.0. In this example, I set `lightBrightness` to 10.0.
![image](https://user-images.githubusercontent.com/93574498/194841200-29fd93d7-57b1-43b4-b880-5c31f0caf5d5.png)

I'm afraid achieving a glare similar to real-life is not possible as of now. After additional HDR support is implemented in BeamNG and with a quality HDR screen, the experience should be more similar to real-life lightning.

**Comment by sainan-zhang** [comment]
OK, I understand. Many thanks for your kind and warm help!
