### ISSUE TITLE
BeamNGpy should provide a Timer Sensor

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#19]
In many occasions, it is important to know the exact time of the simulation. A timer/watch or similar sensor might do it

**Comment by Signaltonsalat** [comment]
I've added a simple timer sensor that gives time relative to the start of the scenario, accounting for possible slowdown/speedup in the simulation (e.g. if you run it at twice the speed of real time, the sensor will also progress twice as fast.)

https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.sensors.Timer

A simple example is in the `examples/west_coast_usa.py` example.
