### ISSUE TITLE
Interaction data between objects

### ISSUE THREAD

**Issue by ASionville** [BeamNG/BeamNGpy#194]
Hey !

How can I fetch the interaction data (force/torque/power/energy) between two objects?

I ask the question in a general case as it could interest someone else, but I would personally like to get a value such as the energy corresponding to the friction force between the tires and the road :
I want to simulate hydroplaning, so I thought a water layer on top of a road might do the trick, and I may get and plot the value over time so that we see the tire losing contact.

**Comment by aivora-beamng** [comment]
Hi, unfortunately it's not possible to get these values directly with BeamNGpy at the moment. This can change over time, if we add the support, I'll post an update here.

It should be possible to get these values using Lua.
General interaction data between two colliding nodes is propagated to the `lua/vehicles/main.lua:onNodeCollision` function, which then propagates the data to the wheel system (`lua/vehicle/wheels.lua:nodeCollision`) and also the controller system. You could create a vehicle controller in Lua that gets the data in the `nodeCollision` collision function, then process it.

Don't know if this is any useful for you, if you have more questions on how to continue with this, please let me know! And sorry for the late answer.

**Comment by ASionville** [comment]
Thanks for the explanation ! It was predictable that the data would not be accessible directly from BeamNGpy.

So I will dive into Lua to create something to work it out.

**Comment by ASionville** [comment]
Okay,
I now understand what the function does, what it handles and how it processes the particle data.
I am thus making a lua module (in extensions) that extracts the data.
How can I make it send values to the python library?

**Comment by aivora-beamng** [comment]
I would recommend to use the TCP connection established between BeamNG.tech and BeamNGpy. You can take a look at the [Using Mods With BeamNGpy](https://github.com/BeamNG/BeamNGpy/blob/master/examples/modInterface/usingmodsWithBNGpy.ipynb) example, and the [corresponding Lua extension](https://github.com/BeamNG/BeamNGpy/blob/master/examples/modInterface/gameEngineCode.lua).

You can also establish an ad-hoc socket to exchange data, using the `luasocket` library which is included with BeamNG.tech.

**Comment by ASionville** [comment]
After spending a while trying to make it work, I'll turn into making the lua itself write into a csv file, it will be more convenient.

I now have a new problem: all my work is for an exam presentation (I have a BNG academic license).
I would like to use game physics as a reasonably accurate example of the forces that apply and the underlying physics.
So I need to be sure the computation obeys physics rules and principles (which I don't doubt at all)
I would then need to look at what equations are used to calculate the forces governing tire/pavement contact.
It would therefore be very useful if you could provide me with the equations used in the calculations.

I understand that this has little to do with this github, so an email exchange is fine if preferred.

**Comment by dstark481** [comment]
Hello ASionville,

I will send an email.

Best regards,
BeamNG Tech Team
