### ISSUE TITLE
Short draw distance from Camera with version 0.27

### ISSUE THREAD

**Issue by Diminati** [BeamNG/BeamNGpy#199]
Hello,
I am using BeamNGpy to generate a video from a forward looking camera mounted on the ego vehicle, for a personal project.
I noticed that the camera provides such a short draw distance; most of the graphic elements are popping up a lot later than I would like.

![image](https://user-images.githubusercontent.com/53713978/208277319-4b8356ab-c134-44e1-9ba3-a9e4eb405d38.png)

I upgraded to 0.27 from 0.24, I didn't have this issue in the past. I couldn't correlate this to any update in the Changelog.
Is there any setting to adjust this rendering distance?
I am willing to sacrifice a little bit of performance to get a nicer image.

Thank you.

**Comment by dstark481** [comment]
Hi Vincent,

The camera contains both a near and far plane value (in metres), which describe the minimum and maximum range which the camera can 'see'.  Here, it looks like the far plane of the camera is too short.  

Currently, as default values, we have `near_far_planes: Float2 = (0.05, 100.0)`.  You can see this for yourself if you look at the constructor in `camera.py`.  

However, you can increase the far plane (the 2nd number) to something like 1000.  For example, when you set the camera up, include `near_far_planes=(0.05, 1000.0)` in the argument list of the function call.  

We will increase this default value for the next release.  This was most likely a typo during coding.

Best regards,
BeamNG Tech Team

**Comment by Diminati** [comment]
Hello Dave,
Thank you very much for your detailed and quick response, modifying near_far_planes did fix my issue.

I think the argument description in the camera class could be a bit more clear.

Great support as always!
Regards,
Vincent
