### ISSUE TITLE
Is there a way to make the buildings in BeamNG's map (in "levels" folder ) have the effect of disaster?

### ISSUE THREAD

**Issue by sainan-zhang** [BeamNG/BeamNGpy#201]
Is there a way to make the buildings in the "level" folder of BeamNG have the effect of disaster? For example, make the undamaged buildings in the map become the buildings after the earthquake, or replace them with other buildings after the earthquake. I really need a building scene after a disaster, such as earthquake, fire or other disasters, but I don't know how to achieve it. Can you give me some suggestions? Looking forward to your reply. Thank you very much!

**Comment by dstark481** [comment]
Hi Sainan,

Thank you for your question.
Unfortunately, we do not model any disasters in the BeamNG simulator, so this is not currently possible.

Best regards,
BeamNG Tech Team
