### ISSUE TITLE
Is there any HD map (e.g. OpenDrive) for BeamNG?

### ISSUE THREAD

**Issue by CAS-LRJ** [BeamNG/BeamNGpy#208]
Hello, I appreciate your great effort to make BeamNG a more realistic simulator. Now I am using it as an simulator for autonommous driving, and I am wondering that if you can provide some HD map files (e.g. opendrive xodr format) to benefit the route planning. Currently, I am using the lua mod #86 to generate global planning, it works but not perfect (the plan is not optimized). For local planning, an alternate method is to use the road definition to draw the local map, however it is not perfect since some roads are not designed as DecalRoad (e.g. tunnels and highway gateways).

**Comment by CAS-LRJ** [comment]
Get it from the new update! Thanks so much!

**Comment by dstark481** [comment]
The OpenDrive exporter is a work in progress, but it should provide any of our maps in .xodr format.  There are some limitations with regards to lanes etc.  Please let us know if you encounter any issues with it.  Any feedback is appreciated.

Best regards,
BeamNG Tech Team
