### ISSUE TITLE
I

### ISSUE THREAD

**Issue by Shaam4146** [BeamNG/BeamNGpy#216]
Is gravity test included in this

**Comment by aivora-beamng** [comment]
Hi, not sure what you mean by "gravity test". There is a possibility to control the gravity with the BeamNGpy library, see the [docs](https://beamngpy.readthedocs.io/en/latest/beamngpy.html#beamngpy.api.beamng.EnvironmentApi.set_gravity)

```python
beamng.env.set_gravity(-9.807)
```
