### ISSUE TITLE
КАКАЯ БУДЕТ САМАЯ ПОСЛЕДНЯЯ ВЕРСИЯ В Beamng_drive

### ISSUE THREAD

**Issue by MoznoSprosit** [BeamNG/BeamNGpy#217]
КАКАЯ БУДЕТ САМАЯ ПОСЛЕДНЯЯ ВЕРСИЯ В Beamng_drive

**Comment by aivora-beamng** [comment]
Hi, this is the issue tracker for the BeamNGpy library, which is used to interface with BeamNG.tech. This question is unfortunately not relevant here.
