### ISSUE TITLE
how to control the traffic lights?

### ISSUE THREAD

**Issue by sainan-zhang** [BeamNG/BeamNGpy#218]
Hi, I don't know if I can control the traffic lights through programming? Or are there any alternative methods to add and control the traffic lights? Can you give me some suggestions? Looking forward to your reply!

**Comment by aivora-beamng** [comment]
Hi,
BeamNGpy does not expose this API yet, in Lua you can get a map's signals data via `core_trafficSignals.getSignalControllers()`.

If a specific one is needed, you can look up the key name in the Traffic Signals tool in the World Editor (menu bar > Gameplay > Traffic Signals)

You can get the states, but you can't set them unfortunately.
