### ISSUE TITLE
Decal roads disappear in the side mirrors

### ISSUE THREAD

**Issue by sainan-zhang** [BeamNG/BeamNGpy#219]
Hi, 
When I used the side mirrors, I chose dynamic reflection in Graphics shown in the following figure. But the decal road in my scene could not be seen and I saw the terrain directly (the terrain color is yellow in my scene and decal road material is asphalt.). I'm very confused about it. Is there any way to fix this? Looking forward to your suggestions. Thank you very much!
![屏幕截图 2023-06-10 090947](https://github.com/BeamNG/BeamNGpy/assets/53167747/22140c8a-dc5d-4f46-9586-77af872733cf)

![2](https://github.com/BeamNG/BeamNGpy/assets/53167747/f8eda403-a1b1-42b1-b146-2195dce36d74)

**Comment by aivora-beamng** [comment]
Hi, decals are not rendered in dynamic reflections due to performance reasons. We will take a look into implementing the support for it in the following versions, but as of now there is no way to render them, unfortunately.
