### ISSUE TITLE
BeamNGpy should provide a way to query simulations state/objects

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#22]
Examples:
- Which cars are in the simulation?
- Which waypoints are in the simulation?

Possibly navigational data of some sort:
- Which streets/roads/etc are in the simulation?

**Comment by Signaltonsalat** [comment]
There is now a general low-level method to find objects of any time in the simulation using the class name ingame: https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGpy.find_objects_class

When you check objects in the F11 editor ingame, you can see that, for example, waypoints have the class `BeamNGWaypoint`. To find these, you could call this method with this class name as the parameter. The same goes for other object. In addition, I've added little helper functions to the scenario class for commond types like the waypoint.
