### ISSUE TITLE
beamngpy.logging.BNGError: No BeamNG binary found in BeamNG home. Make sure any of these exist in the BeamNG home folder: Bin64/BeamNG.tech.x64.exe, Bin64/BeamNG.drive.x64.exe

### ISSUE THREAD

**Issue by RohitVummadi** [BeamNG/BeamNGpy#221]
I do not know what the error is and I have been stuck here for hours. 
![image](https://github.com/BeamNG/BeamNGpy/assets/18355262/3945c672-63cb-4279-bc28-c9c8661a2d16)
![image](https://github.com/BeamNG/BeamNGpy/assets/18355262/6bd8a9e2-2ddf-4f23-940f-6e0032897cc2)

**Comment by aivora-beamng** [comment]
Hi, the `BNG_HOME` variable should be set to the root simulator directory, not to the `Bin64` folder. In your case, you should use `C:\Users\df\Desktop\BeamNG.tech.v0.28.2.0` as the value of the `BNG_HOME` variable.
