### ISSUE TITLE
How to keep the server unclosed to run scripts multi times?

### ISSUE THREAD

**Issue by yuyuyu223** [BeamNG/BeamNGpy#226]
I first executed a program,
```
Beamng.open(launch=True)
......
Beamng.close()
```
I want to execute this program again without closing beamng
But the program that started the second time got stuck in this position:
![image](https://github.com/BeamNG/BeamNGpy/assets/60428269/a126831a-e4b7-40e5-b646-6b06fda3495b)

BeamNG 0.28.2.0.15021
beamngpy 1.26

**Comment by aivora-beamng** [comment]
Hi, we found the source of the issue, it will be fixed in the next version of BeamNGpy.

**Comment by aivora-beamng** [comment]
This is fixed in BeamNG.tech 0.30 and BeamNGpy 1.27, you can update to the latest versions. Feel free to reopen this issue if the problem persists for you.
