### ISSUE TITLE
BeamNG static objects in Scenario

### ISSUE THREAD

**Issue by tariqsameed** [BeamNG/BeamNGpy#23]
BeamNG should provide a method (Programmatic way) to add a static object in the scenario.  For instance, Traffic signals. 

The ScenarioObject class exists but there is no example of it. It will be great if BeamNG provides the explanation of the parameters to ScenarioObject Class.

**Comment by Signaltonsalat** [comment]
The `ScenarioObject` actually didn't allow placing objects at all. Instead, I've added a `StaticObject` class which you can use to place statis meshes from `.dae` files (like the ones used in our levels, and a `ProceduralMesh` class you can use to place procedurally generated meshes, such as a ring or cylinder of a size you can define. An example showcasing this is here: https://github.com/BeamNG/BeamNGpy/blob/master/examples/object_placement.ipynb
