### ISSUE TITLE
About lider sensor

### ISSUE THREAD

**Issue by ccc-fire** [BeamNG/BeamNGpy#231]
### I found an issue. The screen in the game would go dark when the lidar sensor was attached on the car, and I  set the setting is_visualised=false. The scene brightness is not restored, which I thought was a mistake.
![image](https://github.com/BeamNG/BeamNGpy/assets/102889253/3331ef80-5cd7-45a3-a7ef-49449a7efee7)
### When I add lider...
![image](https://github.com/BeamNG/BeamNGpy/assets/102889253/6839e87d-65ba-496b-bea2-0dd8984f2c4f)
#### Maybe someone can help me answer that question.

**Comment by AbdelrahmanElsaidElsawy** [comment]
Hello @ccc-fire 

Thank you for reporting the LiDAR sensor issue affecting the camera view, even when LiDAR visualization is off. Our team is actively working on a fix for the next release. Please feel free to share any additional feedback.

Best regards,

**Comment by aivora-beamng** [comment]
Hi, this issue is fixed for BeamNG.tech 0.30 and BeamNGpy 1.27.
