### ISSUE TITLE
After starting BeamNG.drive with BeamNGpy there is a regular drop in frames

### ISSUE THREAD

**Issue by Dreace** [BeamNG/BeamNGpy#241]
After starting BeamNG.drive with BeamNGpy there is a regular drop in frames, starting it directly is fine.

The normal performance monitoring charts are shown below:
![image_57](https://github.com/BeamNG/BeamNGpy/assets/33168165/81f22da0-599f-46d6-8d25-98479f4ccb85)
![image_58](https://github.com/BeamNG/BeamNGpy/assets/33168165/e5bb17dd-307c-4c43-8571-4b14908eed29)

The performance monitoring charts after starting with BeamNGpy are as follows:
![image_59](https://github.com/BeamNG/BeamNGpy/assets/33168165/a981fec7-c14f-4e6c-b9f0-6514ed4fd44f)
![image_60](https://github.com/BeamNG/BeamNGpy/assets/33168165/817da260-1792-4f2c-b4d2-699670a2307e)
Performance monitoring charts show significantly higher CPU Bookkeeping times (blue raised curve)
Although the average FPS is 60+, the minimum FPS is less than 10.

Use `E:\SteamLibrary\steamapps\common\BeamNG.drive\BeamNG.drive.exe -rport 64256 -nosteam -console -tcom-listen-ip 127.0.0.1 -lua registerCoreModule('tech/techCore') -userpath C: \Users\<username>\AppData\Local\BeamNG.drive` can reproduce the problem. After removing `-lua registerCoreModule('tech/techCore')`, the problem disappears.

It is assumed that the problem is caused by the `tech/techCore` module, but after looking at the code there is no obvious problem.

Version:
BeamNGpy: 1.27.1
BeamNG.drive: 0.31

**Comment by aivora-beamng** [comment]
Hi,

1) I tried the same with BeamNGpy 1.27.1 and BeamNG.drive 0.31 and could not reproduce the performance issue. You say it happens even when BeamNGpy is not running, just when the `techCore` extension is loaded?

2) BeamNGpy 1.27.1 is not compatible with BeamNG.tech 0.31, BeamNGpy 1.28 will be released later this week. Also, we're changing the way of loading the .tech extension in BeamNGpy 1.28 and BeamNG.tech 0.31, the new command-line arguments are:
```bash
Bin64\BeamNG.tech.x64.exe -nosteam -console -lua extensions.load('tech/techCore');tech_techCore.openServer(64256)
```
The old way should still work, but is getting deprecated in the future. Can you try with these arguments and tell me if the problem still occurs?

Thank you for your detailed report.

**Comment by Dreace** [comment]
Thank you for your reply.
I've tried many combinations of situations and the only regular frame dropping occurs when I start my customized scene (with GE lua script) with BeamNGpy, I'll try to find the problem in my code.
