### ISSUE TITLE
Accessing state of siren

### ISSUE THREAD

**Issue by emmettprexus** [BeamNG/BeamNGpy#251]
I'd like to be able to see detect the siren is currently off, on or on with the sound going. I've been looking at the documentation but haven't been able to find anything remotely close.

If the option is not already there, I'd like to contribute so a few pointers in the direct direction and I might be lucky to figure it out! :)

**Comment by aivora-beamng** [comment]
Hi, you can do this using the [Electrics sensor](https://beamngpy.readthedocs.io/en/latest/beamngpy.html#electrics). For a connected vehicle `veh`, the following code should help you to access the data you need:

```python
from beamngpy.sensors import Electrics

veh.sensors.attach(Electrics()) # attach the sensor

veh.sensors.poll() # poll new sensor values
veh.sensors['electrics']['lightbar'] # 0.0 = sirens off, 1.0 = sirens on, 2.0 = sirens on with sound
```

**Comment by emmettprexus** [comment]
Amazing! That's exactly what I need. Thank you! :)
