### ISSUE TITLE
Semantic Segmentation Lane Markings not Showing Up

### ISSUE THREAD

**Issue by prestonbarnett** [BeamNG/BeamNGpy#253]
## Issue Description
I recently started working with `Beamng.tech` and `BeamNGpy` for an academic demonstration with behavior cloning and autonomous vehicles. I started to implement the Camera sensor and was wondering if it's possible to extract lane markings from the semantic segmentation output. I noticed that lane annotation colors are present in the JSON file (e.g., `SOLID_LINE`, etc), but I can't seem to get them to appear on the output of the Camera sensor.

It appears, however, that lane markings are visible in the demonstration in the README. I'm not sure if this is due to a setting or parameter I'm missing. I'd appreciate any help in getting the lane markings to appear as it'll help in training my model on a simplified view of the world for testing purposes.

![image](https://github.com/BeamNG/BeamNGpy/assets/60716321/5525ab09-9ae9-4f25-ad96-2776c3370d27)

## Versions
**Beamng.tech:** 0.31
**BeamNGpy:** 1.28
**OS:** Windows 10 Enterprise

**Comment by alessiogambi** [comment]
@prestonbarnett I am also interested in this issue.

**Comment by alessiogambi** [comment]
@aivora-beamng I also have the problem that procedurally generated roads show up just black. Lane marking also shows up just black (or they do not show up at all). See picture:

![frame_005](https://github.com/BeamNG/BeamNGpy/assets/1557512/699552d5-6690-438e-92c1-a82936e1d1dd)

Could it be that the material I use is not valid?
FYI: I create roads using the `track_editor_C_center` material and the lane markings using: `line_yellow`, `line_dashed_short_yellow`, `line_white`, and `line_dashed_short`

See picture:
![frame_005](https://github.com/BeamNG/BeamNGpy/assets/1557512/0b6ad853-f79d-4b24-b2f1-287cf4571596)

**Comment by alessiogambi** [comment]
@aivora-beamng Is it possible that `Roads` objects do not have a way to set the `ObjectAnnotation` field that one can see from the World Editor? Sadly, I cannot find any existing level where this attribute is set.

**Comment by alessiogambi** [comment]
Quick update: I patched `prefab.json` and hardcoded the `STREET` annotation to all the (Decal) Roads. I can see in the World editor that the label/annotation is the correct one (the color is RED); unfortunately, the annotation and instance cameras always produce the wrong image (see post above).

![image](https://github.com/BeamNG/BeamNGpy/assets/1557512/65ee1cf6-588f-4f2f-abf8-b136e3a3db53)

**Comment by alessiogambi** [comment]
If I put a vehicle in front of the camera I got the following result:
![frame_005](https://github.com/BeamNG/BeamNGpy/assets/1557512/40d4b521-32ad-4e6a-a055-6e58b8d467ed)

The road is still Black, but the vehicle is visible.

**Comment by alessiogambi** [comment]
Since we at it, running the code `https://github.com/BeamNG/BeamNGpy/blob/master/examples/annotation_bounding_boxes.ipynb` produces the expected result  (cannot say anything about the lane markings, tho)

**Comment by alessiogambi** [comment]
I executed the same code on the Italy map using `scenario.add_vehicle(ego, pos=(91, 53, 39), rot_quat=(0.0173, -0.0019, -0.6354, 0.7720))` to place the vehicle. The grey area that corresponds to the asphalt is there, but no lane marking. See picture.

![image](https://github.com/BeamNG/BeamNGpy/assets/1557512/eacde199-99d0-4bac-895a-0ea63b98826f)

One confusing thing is that the World editor says that none of the corresponding roads have any annotation attached to it...

**Comment by alessiogambi** [comment]
@aivora-beamng A quick update. I tried the code using the `template_tech` level (with and without road_insible and after removing the annoying grass field). I changed the zorder and also manually set the annotations in the world editor, but the result is now that instead of an all green image (like the one above) I got an all black image.

**Comment by aivora-beamng** [comment]
Hi @alessiogambi, sorry for the confusion, the `template_tech` level is not the .tech level which is designed to work with the .tech tools. It is called Tech Ground (`tech_ground`), and it will be included as part of the 0.32 BeamNG.tech release. I tested it with the new Road Architect tool designed to create roads, and the annotations are behaving as expected, including the lane markings (we fixed this one for the upcoming release).

![BeamNG drive x64_2024-05-10_16-00-19](https://github.com/BeamNG/BeamNGpy/assets/93574498/a1c3f09c-4782-4b4e-89ec-b407e052a959)
<img width="1024" alt="BeamNG drive x64_2024-05-10_16-00-28" src="https://github.com/BeamNG/BeamNGpy/assets/93574498/fc60cc3d-d1ab-4fbf-b364-46da44904882">

Sorry for the troubles caused, I think it will be best to wait for the release happening soon.

**Comment by aivora-beamng** [comment]
Hi @prestonbarnett, the lane markings are now available in BeamNG.tech 0.32 and BeamNGpy v1.29.

@alessiogambi Try to use the new Tech Ground level released with BeamNG.tech 0.32 today, the annotations should be working much better than on smallgrid.

**Comment by alessiogambi** [comment]
@aivora-beamng As far as I can see, the annotations are working now. (see pictures below).

Note: I updated the tech_ground level because the material I needed (from the west_coast) where missing. 

![frame_081](https://github.com/BeamNG/BeamNGpy/assets/1557512/10b0e1d9-a136-4b96-b5bc-aad3c0a27492)
![frame_081](https://github.com/BeamNG/BeamNGpy/assets/1557512/204837e3-09e5-46bf-958c-6c1554befac5)

**Comment by AbdelrahmanElsaidElsawy** [comment]
If is issue is resolved, we can close this ticket. Thank you for the feedback @alessiogambi @prestonbarnett
