### ISSUE TITLE
Documentation car call names and maps call names

### ISSUE THREAD

**Issue by lucena564** [BeamNG/BeamNGpy#262]
In all of the examples given it has only the default exemple. It is very hard find the way to change that default cars and maps with out know the names used from the coders inside the jsons. </br>
Exemple: List of levels that I can call in the scenario object </br>

```
beamng = BeamNGpy('localhost', 64256, home="path/tech", user=r"./userpath")
beamng.open()

# What are the others options?
scenario = Scenario('industrial_site', 'driver_comfort')

careful = Vehicle('careful', model='T-Series', license='CAREFUL', color='Green')
# aggressive = Vehicle('aggressive', model='T-Series', license='AGGRO', color='Red')
``` 
</br>

About the maps:
```https://documentation.beamng.com/official_content/levels/```
We have all names of region and car, but not in the way that we shoud call.

About the cars:
```https://documentation.beamng.com/official_content/vehicles/```
Same is happening here, what should I use to call a different car?

**Comment by aivora-beamng** [comment]
Hi, to get all the level names, you use the `get_levels` function:
```python
print(beamng.scenario.get_levels())
```

To get all vehicle names, you use the `vehicles.get_available()` function:
```python
print(beamng.vehicles.get_available())
```

You can learn more about the API in [the documentation](https://beamngpy.readthedocs.io/en/latest/).
