### ISSUE TITLE
How put the information on Windshield Display (WSD) or Head-up Display (HUD)?

### ISSUE THREAD

**Issue by PedroAzevedo141** [BeamNG/BeamNGpy#276]
So I'm working with my university to develop a driving simulator that has the ability to create a visualization on the WSD or HUD, but I am having difficulty finding how to get information from the road, such as potholes or speed bumps, and display it.

For example: There is a pothole on the road and I want to notify the vehicle driver about the pothole, how can I do this?"

![Screenshot 2024-07-22 181212](https://github.com/user-attachments/assets/e331173f-92ca-45ff-9123-96a6db8437c2)

**Comment by AbdelrahmanElsaidElsawy** [comment]
Hi @PedroAzevedo141

For creating a visualization on the Windshield Display (WSD) or Head-Up Display (HUD) in your driving simulator, please refer to the BeamNG UI App Creation Documentation. This guide will provide you with the necessary steps and information:

[BeamNG UI App Creation Documentation](http://webdev.gitlab-pages.intranet.beamng.com/documentation/modding/ui/app_creation/)

Best regards,
