### ISSUE TITLE
The Game Does Not Start.

### ISSUE THREAD

**Issue by ThatBeamNGFan** [BeamNG/BeamNGpy#278]
How On Earth Do I Run BeamNG? With Setup.py ? Because That Did Not Work 
I'm On Debian 11 With Python Installed. Tell Me If I'm Doing This Right?

> python3 home/blackloafyt/BeamNGpy-master/setup.py

Should That Work? Just to let you know My Username is " blackloafyt@penguin "

**Comment by AbdelrahmanElsaidElsawy** [comment]
follow the [usage](https://github.com/BeamNG/BeamNGpy?tab=readme-ov-file#usage)

**Comment by AbdelrahmanElsaidElsawy** [comment]
Hi,

As there hasn’t been any further activity on this issue, I’m going to close the ticket for now. If you encounter any more problems or have additional questions, feel free to reopen the issue or start a new one. We’re here to help!

Thank you for using BeamNGpy.

Best regards,
Abdul
