### ISSUE TITLE
Dumping frames should not show additional widgets/graphical elements

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#3]
The various widgets, e.g., speedometer, that are usually shown on the screen might confuse the sefl-driving AI. Hence, they should probably be remove in the frames dumped during the run.

A workaround is to manually disable them once

**Comment by LuisAntonRebollo** [comment]
I assume you are using the "Engine.getColorBufferBase64".

Thx for the report, will be fixed on next update.

**Comment by Signaltonsalat** [comment]
Added [hide_hud](https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGPy.hide_hud) and [show_hud](https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGPy.show_hud) methods.
