### ISSUE TITLE
Export data to CSV table

### ISSUE THREAD

**Issue by vladimirwest** [BeamNG/BeamNGpy#30]
Hi there!
I found that BeamNG could fit well for my research. Now I'm looking for a way to collect data from the game.
In the youtube demonstration from Engineering psychology I found a great example of what i need (1:30-1:35):
![image](https://user-images.githubusercontent.com/24258019/64857388-0ce94f80-d62d-11e9-8d9c-6fafbce67b1d.png)

I want to export at least:
> position
> speed
> wheel angle
> collision between cars (if the car is damaged)

Is there a simple option to export such data to csv?

**Comment by alessiogambi** [comment]
Hi, yes this should be simple enough.

Note that there's a bunch of students doing research on BeamNG.research, and they might have already implemented what you are looking for. 

I can add you to our slack channel Driversity.slack.com if you like, so you can ask them yourself and send a pull request with the solution here.

**Comment by vladimirwest** [comment]
Sure.
Please send it to `vvkilyazov@edu.hse.ru`, thanks!
