### ISSUE TITLE
BeamNGpy and BeamNG.research version mismatch

### ISSUE THREAD

**Issue by TrinityDevelopers** [BeamNG/BeamNGpy#33]
BeamNGpy is the latest from PyPI (1.14.1) and BeamNG.research is the latest one from subversion.  However, this is the warning message I get:

BeamNGpy and BeamNG.* version mismatch: BeamNGpy v1.12, BeamNG.* v1.9
Make sure both this library and BeamNG.* are up to date.
Operation will proceed, but some features might not work.
<beamngpy.beamng.BeamNGpy object at 0x000002B1B6F94048>

Is there a newer version of BeamNG.research somewhere else?

**Comment by pascale-commits** [comment]
Given that the issue is one year old, I hope that you managed to resolve it. 
Please comment if the issue persists and I will provide a more timely support.
