### ISSUE TITLE
Dynamically spawing cars in the simulation

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#40]
Tools like traffic tool can dynamically spawn cars in running games/simulations. Maybe we can add the same feature to BeamNGpy?

**Comment by Palculator** [comment]
Control over the traffic tool has been added in v1.16. It requires you to spawn vehicles you want to participate in traffic yourself, however, but spawning vehicles after the scenario was started was already supported (if you call `add_vehicle` on a loaded scenario, it spawns it at runtime.) I'll probably write an example at some point but for now the unit test for it shows an example use: https://github.com/BeamNG/BeamNGpy/blob/master/tests/test_vehicle.py#L254

Docs here: https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGpy.start_traffic

This version also added a method to query the game about available vehicles to make this easier, so you can ask the game for available vehicles and randomly select some to spawn: https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.beamng.BeamNGpy.get_available_vehicles
