### ISSUE TITLE
BeamNG should allow for multiple connections

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#48]
At the moment, only one BeamNGpy instance can be used to connect to a simulation. It would be ideal if, at least for vehicles, one can use multiple sockets/end-points, such that one BeamNG instance might be used to control the scenario while the others control the vehicles?

**Comment by Palculator** [comment]
You are right, this would be neat. However the code is mostly written with the Python side acting as the server, BeamNG.drive as the client. In hindsight this was a mistake I made early on, but it's one I have to deal with now so it could take a bit to rework everything to allow multiple concurrent clients.

**Comment by Palculator** [comment]
Added in v1.19.1: https://github.com/BeamNG/BeamNGpy/blob/master/CHANGELOG.rst
Example here: https://github.com/BeamNG/BeamNGpy/blob/master/examples/multi_client.ipynb
