### ISSUE TITLE
Customize Car Attributes

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#50]
During the simulation, there might a need to change some attributes of the vehicles. For example, their color, their components (wheels, spoilers, etc). This can be used to create rich driving simulations while keeping the overall computational cost low (to some extent, the traffic plugin does this). As @pascale-commits says, while spawning a vehicle, color attributes can be defined on-the-fly, which is good; however, I wonder if there's the possibility to change some attributes of cars also without respawning them. 

> Why this might be important/relevant?

Because the user does not have to "recompute" or respawn the vehicle in the exact condition every time just to change
an attribute that does not impact the physics of the vehicle itself (i.e., color). Said in other words, the user should not do the work of the simulator and replace moving vehicles on the fly.

> What attributes can be effectively (easily) changed of a vehicle?

I understand that color is one of such attributes, but what about skins, the color of wheels/rims, windshield, etc.? I assume that any other modification will impact somehow accurately simulating the physics (i.e., the aerodynamics of the car, type/size/material of the wheels, etc.).

**Comment by alessiogambi** [comment]
Hi, thanks for the example.

> As far as I can see the python API does not support the configuration of any other vehicle properties but it is possible to change them in-game, though I guess this is not what you're interested in.

Actually, this is exactly what I am interested in. Maybe I should open a different issue or refine the description of this one?

**Comment by pascale-commits** [comment]
Please add a more detailed description of what you are searching for :) I've reopened the issue.

**Comment by pascale-commits** [comment]
Thanks for specifying. 

It is possible to change main color of a car on the fly in the game. This is supported by the beamngpy lib through the <set_color> method of the vehicle class.
Changing other colors on the fly is not supported at the moment, but it is possible to change the available vehicle colors manually in the game in a given level by pressing ESC -> Selecting Vehicle Config -> Select Color Tab and adjusting the colors to your needs.

Setting new skins triggers a vehicle reload, so it is not possible to change them on the fly.

Yes, it is not possible to change any part of the vehicle that affects the deformation mesh. It is not possible to transfer the damage/deformation of  one beam structure to another.

**Comment by alessiogambi** [comment]
Great. Thanks for the clarification!
