### ISSUE TITLE
AI Traffic creation from BeamNGpy

### ISSUE THREAD

**Issue by vladimirwest** [BeamNG/BeamNGpy#52]
Hello!

Is it possible to create AI traffic from BeamNGpy which could be launched together with a player-controlled car?
Can you share a code example if it is possible?

**Comment by ASionville** [comment]
Take a look here :
https://github.com/BeamNG/BeamNGpy/issues/40#issuecomment-638174494

**Comment by pascale-commits** [comment]
It seems like this issue has been resolved. Thanks for your input.
