### ISSUE TITLE
BeamNG.research version 1.16 breaks Decalroad positioning

### ISSUE THREAD

**Issue by masskro0** [BeamNG/BeamNGpy#53]
If you add several Decalroads to the prefab file by using the scenario.add_road function, then they all spawn at (0,0) even though their start and endpoint are different. The same prefab file works fine for BeamNG.research version 1.15. There are no error messages in the BeamNG console.
Prefab file: https://pastebin.com/LXL7Vp7r
![roads](https://user-images.githubusercontent.com/49821640/85434277-145b6300-b586-11ea-9b11-21231ab6c4eb.jpg)

**Comment by Palculator** [comment]
This was caused by some changes in how the game actually handles DecalRoads. There's a fix in the `dev` branch which I'll merge soon.
