### ISSUE TITLE
BNGValueError Scenario Not Found - But the game proceeds to load the scenario fine.

### ISSUE THREAD

**Issue by BleedObsidian** [BeamNG/BeamNGpy#56]
Once the game connects to the python server and the "load_scenario()" call is made. The game returns a BNGValueError about not being able to find the scenario (this then means the python can not continue) but the game loads the scenario fine?

![image](https://user-images.githubusercontent.com/2222870/86035447-45c7a900-ba34-11ea-91f1-a84ca8b13889.png)

![image](https://user-images.githubusercontent.com/2222870/86035467-4d874d80-ba34-11ea-9b9f-b02c7bb53be2.png)

Any ideas why this is happening? Im currently trying to dig through the lua to prevent the failed to load error being sent to the python server.

**Comment by BleedObsidian** [comment]
I'm stumped on this one, I had a wild attempt of placing the BeamNGPy.zip mod file in the mods folder for the full steam BeamNG game and I managed to get much further. The scenario is recognised as found and the python server is told so successfully.

However everything works except from the research specific features such as LiDar and I imagine many other things such as cameras:

![image](https://user-images.githubusercontent.com/2222870/86069158-ff446f80-ba70-11ea-9f14-7e6a6a33acaa.png)

I assume this is why there is a research specific BeamNG version. Everything is leading me to believe that the svn repository for BeamNG.research is wildly out of date or in a corrupt state of broken?

@Palculator

**Comment by alessiogambi** [comment]
@BleedObsidian what version of beamng research are you using? Does beamngpy warn you about a version mismatch between the api and the simulator?

Note that despite being base on the same technology the game and the simulator are different beasts. I believe it might be hard to make the game behave as the research version and the other way around.

**Comment by BleedObsidian** [comment]
Hi @alessiogambi, thanks for the reply.

I'm using the latest version of BeamNG.research (revision 15 of the svn repository) and this is the version information from the console: `v 1.4.0.0.0 - x64 - build 0 - 6/30/2020`

For the version of BeamNGPy, i'm using the latest available from the python pip3 repository, 1.16.3. Which I'm now realising might be out of date, let me trying using the latest BeamNGPy from source.

In terms of getting a version mismatch error, I do not.

**Comment by BleedObsidian** [comment]
@alessiogambi 

I've just tried installing the pip package from source and also from the dev branch. Same issue.

It doesn't make much sense to me, I can confirm that both BeamNGPy and BeamNG.research are using the correct user path.

I've also tried on a brand new machine from scratch with a fresh install of BeamNG.reserach and BeamNGPy, im getting the same issue? I'm sure this issue can't just be me.

**Comment by Firestorm7893** [comment]
I'm having the exact same issue, i even tried going into beamng.py and hardcoding the path to the scenario but nothing works

**Comment by BleedObsidian** [comment]
@Firestorm7893 

Really glad this isn't just me!

It's been driving me nuts to try and figure this out. I'm really keen to use this as a simulator for my dissertation next year but I just can't get it to work.

**Comment by BleedObsidian** [comment]
@Firestorm7893 @alessiogambi @Palculator

I've found a fix for the issue. I have no clue how anyone has been using BeamNG.research recently, this bug should be affecting everybody.

In ResearchGE.lua:

![image](https://user-images.githubusercontent.com/2222870/86196025-2753d180-bb4a-11ea-96aa-1ffd2ce35c6c.png)

If the value of `scenariosLoader.startByPath()` returns nil, then the scenario is assumed to have not been found. However, the value of  `scenariosLoader.startByPath()`  **always returns nil**...

In lua/ge/extensions/scenario/ScenariosLoader.lua:

![image](https://user-images.githubusercontent.com/2222870/86196212-a6490a00-bb4a-11ea-9cae-b88870b470c2.png)

In my console logs posted earlier, you can see that the message `log('E', logTag, path .." does not exist")` did not appear in the console. This told me that `FS:fileExists(path)` was clearly passing and the game was successfully loading the scenario.

Adding a `return true` fixed the issue and no longer falsely sends a BNGValueError to the python server and everything is now working perfectly:

![image](https://user-images.githubusercontent.com/2222870/86196327-ee682c80-bb4a-11ea-94a0-68a274bd5ce8.png)

The only problem is, only BeamNGPy appears to be open source and this file is clearly part of the BeamNG core lua API. This means I can't make a pull request to fix the issue without moving the file checks to the ResearchGE.lua file which isn't a very clean solution. Will the devs please update and include this fix in ScenarioLoader.lua?

**Comment by BleedObsidian** [comment]
I've just checked the ScenarioLoader.lua for the most recently copy of the steam version of BeamNG.drive and the return true is already there! This clearly is showing that the SVN repository is out of date or broken along with the missing proceduralPrimitives.lua file: https://github.com/BeamNG/BeamNGpy/issues/55

**Comment by BleedObsidian** [comment]
Closing this issue as it is only a problem with the publicly available SVN repository version, a fully working version is available when contacting: research@beamng.gmbh
