### ISSUE TITLE
Change Environmental Properties

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#64]
It would be cool/nice if BeamNGpy let us change the time-of-day, the sky, and the weather (or any other environmental properties that can be configured throughout the world editor)

**Comment by masskro0** [comment]
In beamng.py there is a function called "set_weather_preset" where you can load a weather preset from art/weather/default.json. You can add your own presets as well. This function also allows to change the time of day. Otherwise you can change it via the function "set_tod(tod)".

**Comment by alessiogambi** [comment]
I see. Should the user ensure that some definition of weather (e.g., heavy rain, light rain) are provided **before** the simulation is started or the various weather conditions will be always available and can be changed on-the-fyl?

**Comment by masskro0** [comment]
You can call this function right after bng.load_scenario. Also, you can change it on-the-fly but it takes a few seconds to load the weather preset.

**Comment by pascale-commits** [comment]
Closing, since this issue seems to be solved. Thanks for you input.
