### ISSUE TITLE
Winds

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#65]
I am not sure if this is even possible... but can we create "winds"

**Comment by pascale-commits** [comment]
Yes, that is possible.

It's not supported through the library, but the game has an app called 'Winds!', which you might be interested in.

**Comment by alessiogambi** [comment]
Great. I'll have my students looking into that

**Comment by pascale-commits** [comment]
The app uses the obj:setWind function on the vehicle engine side.
