### ISSUE TITLE
set_steps_per_second does not affect temporal resolution of the simulation

### ISSUE THREAD

**Issue by Fezward** [BeamNG/BeamNGpy#75]
According to the docs set_steps_per_second should set the temporal resolution of the simulation, eg. for sps=2 each step should advance the simulation by 0.5 seconds. However step(1) always advances the simulation by 0.05 seconds. set_steps_per_second only affects the realtime of one step, not the simulation time (the framerate is noticeably lower for low sps).
This issue can be reproduced using the following code (the expected simulation time would be 2 seconds):

from beamngpy import BeamNGpy, Scenario, Vehicle
from beamngpy.sensors import Timer

sps = 100
n = 200
bng = BeamNGpy('localhost', 64256)
bng.open(launch=True)
bng.set_deterministic()
bng.set_steps_per_second(sps)
scenario = Scenario('smallgrid', 'test')
vehicle = Vehicle('ego', 'etk800')
timer = Timer()
vehicle.attach_sensor('timer', timer)
scenario.add_vehicle(vehicle)
scenario.make(bng)
bng.load_scenario(scenario)
bng.pause()
bng.start_scenario()
bng.step(n)
sensors = bng.poll_sensors(vehicle)
print('Time passed according to the vehicle timer is {} seconds.' . format(sensors['timer']['time']))
input('Press enter when done')
bng.stop_scenario()
bng.close()

**Comment by Palculator** [comment]
Hey, thanks for reporting. This should be fixed in the 1.17.1 release I just pushed & uploaded to PyPI.
