### ISSUE TITLE
BeamNG Keyboard input not working?

### ISSUE THREAD

**Issue by umerhamdan10** [BeamNG/BeamNGpy#76]
My keyboard inputs are not working like view_camera, drive car manually etc

**Comment by ASionville** [comment]
I got the same, do you have any controller plugged in ?

**Comment by pascale-commits** [comment]
Can you post the code you're using and post or send the log file to my mail address?
It's pmaul(a)beamng.gmbh.

**Comment by pascale-commits** [comment]
And please specify what version you are using of BeamNG.research and BeamNGpy

**Comment by umerhamdan10** [comment]
sorry i did not solve this problem

**Comment by pascale-commits** [comment]
Yes, I'm here to help solving this problem, I'm from the company :)

**Comment by pascale-commits** [comment]
I've addressed one possible solution [here](https://github.com/BeamNG/BeamNGpy/issues/72#issuecomment-756188305).
Please reopen this issue if your experience differs from the one addressed in issue 72.
