### ISSUE TITLE
A note on the usage of BeamNG.research

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#77]
I stumbled upon this just now... It was so obvious I did not realize it soon.

BeamNG.research needs access to local network, so the Windows firewall must be configured to let BeamNG (and BeamNG.py) create connections and listen for incoming connections (at least on the private network).

This raises the question of whether there should be a FAQ section in the README.mf

**Comment by Palculator** [comment]
Added a note about the windows firewall to the README :)
