### ISSUE TITLE
Error with ai_set_line method

### ISSUE THREAD

**Issue by masskro0** [BeamNG/BeamNGpy#81]
Calling the method vehicle.ai_set_line() method gives me the following error:
016.108|E|libbeamng.Lua.Exception|lua/vehicle/ai.lua:1179: attempt to get length of upvalue 'wpList' (a nil value)
016.110|E|libbeamng.Lua.Exception|=============== Stack Traceback >> START >>
016.110|E|libbeamng.Lua.Exception|(1) metamethod C function '__len'
016.111|E|libbeamng.Lua.Exception|(2) Lua upvalue 'validateInput' at file 'lua/vehicle/ai.lua:1179'
016.111|E|libbeamng.Lua.Exception|  Local variables:
016.112|E|libbeamng.Lua.Exception|  (*temporary) = nil
016.113|E|libbeamng.Lua.Exception|  (*temporary) = number: -0.05
016.113|E|libbeamng.Lua.Exception|  (*temporary) = number: 0.05
016.114|E|libbeamng.Lua.Exception|  (*temporary) = number: -1.23305e-05
016.114|E|libbeamng.Lua.Exception|  (*temporary) = number: 0.865996
016.115|E|libbeamng.Lua.Exception|  (*temporary) = number: -0.500051
016.115|E|libbeamng.Lua.Exception|  (*temporary) = number: -1.23305e-05
016.116|E|libbeamng.Lua.Exception|  (*temporary) = number: 9.2762e-312
016.117|E|libbeamng.Lua.Exception|  (*temporary) = C function: builtin#163
016.117|E|libbeamng.Lua.Exception|  (*temporary) = number: 4.44659e-322
016.118|E|libbeamng.Lua.Exception|  (*temporary) = string: "attempt to get length of upvalue 'wpList' (a nil value)"
016.118|E|libbeamng.Lua.Exception|(3) Lua field 'updateGFX' at file 'lua/vehicle/ai.lua:1529'
016.119|E|libbeamng.Lua.Exception|  Local variables:
016.119|E|libbeamng.Lua.Exception|  dtGFX = number: 0.05
016.120|E|libbeamng.Lua.Exception|  tmpPos = userdata: 0x01b52e726ae8
016.120|E|libbeamng.Lua.Exception|(4) Lua function 'onGraphicsStep' at file 'lua/vehicle/main.lua:78' (best guess)
016.121|E|libbeamng.Lua.Exception|  Local variables:
016.122|E|libbeamng.Lua.Exception|  dtSim = number: 0.05
016.122|E|libbeamng.Lua.Exception|--------------- << END <<
016.123|E|libbeamng.Lua.Exception|******************************************
016.123|E|libbeamng.Lua.Exception|*** DISABLING VEHICLE DUE TO EXCEPTION ***
016.124|E|libbeamng.Lua.Exception|******************************************

I tried both calling from Lua and Python, both result in the same error. I'm using beamngpy 1.18 with the newest BeamNG.research version (1.7.0.0). However, this function worked fine with beamngpy 1.15 and BeamNG.research version (1.5.0.0).

**Comment by pascale-commits** [comment]
`ai_set_line` is outdated atm, use `ai_set_script` instead:
[documentation](https://beamngpy.readthedocs.io/en/latest/api/beamngpy.html#beamngpy.vehicle.Vehicle.ai_set_script), [example](https://github.com/BeamNG/BeamNGpy/blob/master/examples/ai_line.py)
