### ISSUE TITLE
Socket will D/C during loading, making the lib useless

### ISSUE THREAD

**Issue by DaRealCodeWritten** [BeamNG/BeamNGpy#84]
I can't use the BeamNGpy library since for some odd reason, while loading a scenario, the socket will timeout and the BeamNG.research console will get spammed with trying to connect, then failing, over and over again, is there any way to avoid the socket timing out?

**Comment by pascale-commits** [comment]
What is you setup (OS, Beamngpy version, BeamNG.research version), are you using the newest one?
Can you post your code?

**Comment by alessiogambi** [comment]
@DaRealCodeWritten Check your firewall configurations as by default might deny any "untrusted" connections, including the ones from/to localhost.

**Comment by DaRealCodeWritten** [comment]
@alessiogambi i already allowed Python and Beam through the firewall

**Comment by pascale-commits** [comment]
Please post your code and logfiles (you may also send the log files to: pmaul(a)beamng.com).

**Comment by DaRealCodeWritten** [comment]
@pascale-commits Apologies for not responding, my PC has been down (and still is). I got beam working properly now though

**Comment by pascale-commits** [comment]
Good to hear, do you know what the issue was and how did you resolve it?
