### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#87]
Hi, not sure if this issue belongs here.

Since now we can download all the releases, I wonder whether there's the possibility to avoid downloading all the assets every time. I like that each release is self-contained, but also, I do not like that I need to download 6GB each time, most of which is likely the same content I have from previous versions.

I do not have a solution yet for this, maybe the release can be divided into "all", "engine" and "data" something?

**Comment by pascale-commits** [comment]
Hello, thanks for the suggestion. We discussed the feature request but decided to not implement it.
