### ISSUE TITLE
Software does not start and fail silently when home folder contains space

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#95]
Hi, I am not sure if this is mentioned anywhere, but with 1.7.0.1 we could not run BeamNG.research when the user path has an empty space.

We figured this out after some trial and error (from the console/command line): we manually started BeamNG.research by adding and removing the usual options (-console, -rport, etc). Removing the -userpath one made it work.

Maybe there's a way to handle this at the API level?

**Comment by pascale-commits** [comment]
Thanks for the report. We are working on it.

Another way of using the simulation with manual startup is to call `beamng.open('launch=False')`.

**Comment by alessiogambi** [comment]
FYI. We resorted to let user change the location of beamng user folder.

**Comment by Palculator** [comment]
I thought this was a problem in BeamNGpy but it turns out the failure is actually in BeamNG.tech. I've added a note about it to the README and moved the issue to our internal BeamNG.tech issue tracking. Since it's not really related to BeamNGpy I'll close this issue.
